feat(icons): own heroicons library (DEV-500)
dasch-swiss/dsp-cpe-app pull request #17
Opened 2022-02-17 16:01 UTC by EricSommerhalder

resolves DEV-500

Maybe we should add a make command to update the heroicons or implement some kind of listener that checks for updates on the elm-heroicons repository.

2022-02-23 08:45 UTC, kilchenmann commented
As discussed in the weekly meeting, the script should be (maybe) a shell script that we do not have to install additional tools like python. But we have to wait with the icons for the moment. Rebecca wrote me, that she wants to user an other library than the heroicons.

2022-03-03 09:07 UTC, mdelez requested changes

2022-03-03 16:15 UTC, EricSommerhalder commented on get-heroicons-list.sh
> +echo -e "$OUTPUT" > "src/Icon.elm"
Done

2022-03-03 16:35 UTC, mdelez approved these changes
Thanks! You are my hero-icon :)

2022-03-03 16:35 UTC, merged