Wip/dev 482 navigation module
dasch-swiss/dsp-cpe-app pull request #28
Opened 2022-03-21 11:33 UTC by domsteinbach

resolves DEV-482

2022-03-23 13:17 UTC, mdelez requested changes
It's a good first implementation but we should all have a meeting about how we are going to implement CSS

2022-03-23 13:17 UTC, mdelez commented on src/NavigationHeader/HeaderModule.elm
> +-- Container for al left elements
al -> all

2022-03-23 13:17 UTC, mdelez commented on src/NavigationHeader/HeaderModule.elm
> +-- the mobile menue container. Hidden if the screen size reaches medium size
menue -> menu

2022-03-23 13:17 UTC, mdelez commented on src/NavigationHeader/HeaderModule.elm
> +primary : Css.Color
are these colors used? You also have the same in `CssColors`

2022-03-23 13:17 UTC, mdelez commented on src/NavigationHeader/Navitem.elm
> +    , hRef : String -- set to "#" if you like to run sth via onClick
hRef -> href

2022-03-23 13:17 UTC, mdelez commented on src/NavigationHeader/SearchBar.elm
> +-- class="block w-full pl-10 pr-3 py-2 border border-transparent rounded-md leading-5 bg-gray-700 text-gray-300 placeholder-gray-400 focus:outline-none focus:bg-white
can the commented out code be removed?

2022-03-23 13:17 UTC, mdelez commented on src/NavigationHeader/HeaderModule.elm
> +navHeaderBgCt : List (Attribute msg)
It's a small thing, but using `ct` as the shorthand for `container` isn't really clear. Perhaps `cntr` would be better.

2022-03-23 13:27 UTC, domsteinbach commented on src/NavigationHeader/HeaderModule.elm
> +navHeaderBgCt : List (Attribute msg)
good with that. It is an eary draft though, hence all css and how we implement it is not yet clear and how the buttons needed do not yet support anything.

2022-03-29 09:05 UTC, mdelez approved these changes
Thanks!

2022-03-29 09:06 UTC, merged