feat (buttons): adds button functionality (Dev-691)
dasch-swiss/dsp-cpe-app pull request #31
Opened 2022-03-29 10:10 UTC by domsteinbach

resolves DEV-691

2022-03-29 13:58 UTC, mdelez requested changes
I gotta be honest, I really don't like this 'ToUnstyled' version of each button. Perhaps we only need this temporarily but can't we just change everything to use `Html.Styled` and then each button will have `\> toUnstyled` at the end?

2022-03-29 13:58 UTC, mdelez commented on src/Buttons/Button.elm
> +primaryButtonUnStyled : List (Attribute msg) -> String -> BasicButtonSize -> Html msg
UnStyled -> Unstyled

2022-03-29 13:58 UTC, mdelez commented on src/Buttons/Button.elm
> +secondaryButtonUnStyled : List (Attribute msg) -> String -> BasicButtonSize -> Html msg
UnStyled -> Unstyled

2022-03-30 05:53 UTC, domsteinbach commented on src/Buttons/Button.elm
> +primaryButtonUnStyled : List (Attribute msg) -> String -> BasicButtonSize -> Html msg
I do not like it either. Having it temporarily was the idea. There is need to change the all the modules/components which use Html to Htlm.Styled as well as all other modules which return the toUnstyled version. This is only a step on the path.

2022-04-04 14:17 UTC, closed without merging

2022-04-04 14:19 UTC, domsteinbach commented
Closed due to a lot of refactoring by using own css classes.