feat (functionality): add missing button functionality (DEV-691)
dasch-swiss/dsp-cpe-app pull request #34
Opened 2022-04-06 08:41 UTC by domsteinbach

resolves DEV-691

2022-04-06 09:37 UTC, mdelez requested changes

2022-04-06 09:37 UTC, mdelez commented on src/CustomCss/DaschTailwind.elm
> +dtwClass : List String -> Attribute msg
It's not very clear to me what this is for and it doesn't appear to be used in the code, can you provide an example? also, I think functions in this module shouldn't include `dtw` since that is what we name the import so `Dtw.dtwClass` looks a bit strange.

2022-04-06 09:37 UTC, mdelez commented on src/CustomCss/DaschTailwind.elm
> +-- adds the passed event as prefix to every class string and concadinates all to one class string
concadinates -> concatenates

2022-04-06 09:37 UTC, mdelez commented on src/Buttons/BasicButtons/BasicButton.elm
> +        , Dtw.onFocus
This looks much nicer! 😄

2022-04-06 14:58 UTC, domsteinbach commented on src/CustomCss/DaschTailwind.elm
> +dtwClass : List String -> Attribute msg
It is a helper function used all over in the header component (user menu branch).
It is used for defining styles like so: 

`navHeaderBgCntrStyle =
    [ Dtw.bg_white
    , Dtw.shadow
    , ... 
    ]
        |> dtwClass`
        
... and use such a  style directly in an Html element, e.g.

`nav [ id "nav-header-bg-cntr", navHeaderBgCntrStyle ]`

I think it is quite comfy to not overload the Html elements.

2022-04-07 09:52 UTC, mdelez commented on src/CustomCss/DaschTailwind.elm
> +dtwClass : List String -> Attribute msg
ah, well then this should be a part of the PR you will open for the user menu module since it's not used in any of the code in this PR. I looked at your user menu module branch and there is a lot of mix and matching going on currently. We should all agree on one way to apply class names.

<img width="1061" alt="Screen Shot 2022-04-07 at 11 36 51" src="https://user-images.githubusercontent.com/60604010/162172479-2d36e720-fcd8-4b2b-bd61-d155e85b64aa.png">

However, I don't see what makes this much different from the existing `classList` function. This new method makes it so that you don't have to use the `class` attribute in the Html element but I find it easier to read with the `class` attribute. If we only need to apply one class then we can write `class Dtw.bg_indigo` and if we need to apply multiple classes we can write `class Dtw.classList [ Dtw.bg_indigo, Dtw.flex ]` (or you can have a function that returns this list to reduce the clutter) so like `class Dtw.classList navHeaderBgCntrStyle`. But all of this is just my opinion and we should see what @EricSommerhalder thinks since he is also applying a lot of tailwindcss classes in his branch.

2022-04-07 09:52 UTC, mdelez commented on src/CustomCss/DaschTailwind.elm
> +-- adds the passed event as prefix to every class string and concadinates all to one class string
done in [964966e](https://github.com/dasch-swiss/dsp-cpe-app/pull/34/commits/964966e31a4faa437256b13e9933ae9123636319)

2022-04-07 12:17 UTC, domsteinbach commented on src/CustomCss/DaschTailwind.elm
> +dtwClass : List String -> Attribute msg
Yeah, there is no big difference to Dtw.classList, but I prefered it shorter with less code.
I also thought that for one class we use `class "[my-class]"` directly. Using everything in a similar fashion with "class" in the template makes it more verbose and clear though. That's preferable, I agree. So I am happy to change everything to this pattern:

`myClassesString = Dtw.classList [ Dtw.bg_indigo, Dtw.flex, ... ]` 

 `div [class myClassesString] [ text "lorem ipsum"]`

2022-04-07 12:21 UTC, domsteinbach commented on src/CustomCss/DaschTailwind.elm
> +dtwClass : List String -> Attribute msg
For now and here I simply removed the helper function hence it is not used.

2022-04-07 12:25 UTC, domsteinbach commented on src/CustomCss/DaschTailwind.elm
> +dtwClass : List String -> Attribute msg
done [here](https://github.com/dasch-swiss/dsp-cpe-app/pull/34/commits/362e24aba199053103a341f6f547d34e5344efa0)

2022-04-07 12:40 UTC, mdelez approved these changes
looks good, thanks!

2022-04-07 12:48 UTC, merged