feat (Navigation header): toggle search bar and nav items (Dev-794 )
dasch-swiss/dsp-cpe-app pull request #52
Opened 2022-05-03 13:49 UTC by domsteinbach

resolves DEV-794

2022-05-04 09:06 UTC, EricSommerhalder reviewed
Functionality is perfect. Some comments about structure and small clean up stuff

2022-05-04 09:06 UTC, EricSommerhalder commented on src/Projects/TailwindPlayground.elm
> +import NavigationHeader.Model as H
Not a fan of the short of a name, makes it harder to read imo

2022-05-04 09:37 UTC, mdelez requested changes
Works well for me also but I've added my thoughts and some change requests

2022-05-04 09:37 UTC, mdelez commented on src/NavigationHeader/Model.elm
> +    { uId : String
I don't think the 'u' is necessary in the property names since it's inside of the `User` type alias

2022-05-04 09:37 UTC, mdelez commented on src/NavigationHeader/Navbar.elm
> +renderNavItems nb =
for readability reasons, I would rename `nb` to something more clear like `navItems`

2022-05-04 09:37 UTC, mdelez commented on src/NavigationHeader/Navbar.elm
> +getStyleForState : Bool -> Attribute msg
this can be simplified to a local variable inside `navItem`

2022-05-04 09:37 UTC, mdelez commented on src/NavigationHeader/UserMenuModule.elm
> +import NavigationHeader.Model exposing (Msg(..))
Might be a good idea to name the import to something like `NavHeader` and then you can write `NavHeaderModel.Msg` so it's more clear but like Eric said previously, I think it's better if we don't split Model/View/Update into separate modules so then you can write `NavHeader.Msg`

2022-05-04 09:37 UTC, mdelez commented on src/NavigationHeader/View.elm
> +                , div [ id "user-menue-cntr" ] [ userMenu header.user ]
menue -> menu

2022-05-04 09:37 UTC, mdelez commented on src/NavigationHeader/View.elm
> +    if showSb == True then
I'm pretty sure the old way works the same way. I use it in my code without any issues. You don't need to explicitly write `== True`.

2022-05-04 09:37 UTC, mdelez commented on src/NavigationHeader/View.elm
> +showButton show =
This would be better as a local variable inside `view`. `== True` also isn't necessary.

2022-05-04 09:37 UTC, mdelez commented on src/Projects/TailwindPlayground.elm
> +init : ( Model, Cmd msg )
@EricSommerhalder should this remain `Msg` or is `msg` fine?

2022-05-04 09:37 UTC, mdelez commented on .gitignore
> +src/.DS_Store
@EricSommerhalder I think it's fine since it prevents this file from ever becoming a part of the repository. The link also suggests this method of adding it to the gitignore. Are you talking about disabling the creation of the file on our systems?

2022-05-04 13:14 UTC, EricSommerhalder commented on .gitignore
> +src/.DS_Store
That's what I was talking about yes. But if you guys both don't mind having it in gitignore I can live with it :)

2022-05-04 13:18 UTC, EricSommerhalder commented on src/Projects/TailwindPlayground.elm
> +init : ( Model, Cmd msg )
msg is fine since we don't send a Command at the moment. However in the Main file (line 84) we're already ready for Playground messages, so if the init of Playground will change in the future, we could be ready for it by keeping Msg here. For the moment, I think its fine though.

2022-05-09 08:35 UTC, domsteinbach commented on src/NavigationHeader/Model.elm
> +    , href : String -- set to "#" if you like to run sth via onClick
This is a common way of not routing/refreshing if there is not an href set. For running an onClick on a nav tag this is also the way unless you like to reload. Of course this is actually not the purpose of a nav and it is not intended by me nor do I like to recommend this usage. So just don't use it. :-)

I made navs according to the requirements of our UX. But what if we need to send a msg or a cmd onClick and not route to the link? By using navs this is the way to achieve it. We could also not use navs instead or simply not use any onClick in the navbar.

For resolving this, I can remove the comment (which was introduced way back).

2022-05-11 08:39 UTC, domsteinbach reviewed
Changed everything to the new architecture

2022-05-11 08:39 UTC, domsteinbach commented on src/Projects/TailwindPlayground.elm
> +import NavigationHeader.Model as H
Done

2022-05-11 15:40 UTC, EricSommerhalder approved these changes
Thanks a lot i really like the changes. I also think its nice to have everything in one headerfile. One comment to discuss on Monday.

2022-05-12 09:56 UTC, domsteinbach commented on src/DspCpeApi.elm
> +    Header.view headerModel
That's exactly what came to my mind yesterday and I absolutely do not wan't to use the model here ...  I'll change it for sure according to the Api's purpose (which I like btw. It minimises circular dependencies, imports, constructor functions, ... and it keeps a projects page clean and clear)

2022-05-12 10:27 UTC, domsteinbach commented on src/DspCpeApi.elm
> +    Header.view headerModel
Changed in the latest commits.

2022-05-12 11:40 UTC, domsteinbach commented on src/NavigationHeader/Model.elm
> +    { uId : String
Changed.

2022-05-12 12:08 UTC, mdelez approved these changes

2022-05-12 12:49 UTC, merged