feat(button): circular button incl. icons
dasch-swiss/dsp-cpe-app pull request #6
Opened 2022-02-08 09:50 UTC by kilchenmann

resolves DEV-444

2022-02-09 08:02 UTC, EricSommerhalder requested changes
Looks good to me, two minor comments.

2022-02-09 08:02 UTC, EricSommerhalder commented on src/TailwindPlayground.elm
> +            , CircularButton.view { size = Buttons.Shared.ExtraSmall, icon = "annotation" }
If I understand it correctly, this can be replaced by the Buttons.Button.circular method?

2022-02-09 08:22 UTC, kilchenmann commented on src/TailwindPlayground.elm
> +            , CircularButton.view { size = Buttons.Shared.ExtraSmall, icon = "annotation" }
Yes that's right. This will be resolved in DEV-483

2022-02-09 08:26 UTC, kilchenmann commented on src/Buttons/CircularButton.elm
> +import Html.Styled as Html
resolved in 0d40882

2022-02-09 12:59 UTC, EricSommerhalder approved these changes
Perfect, thank you!

2022-02-09 14:52 UTC, subotic approved these changes

2022-02-09 14:56 UTC, kilchenmann commented on src/TailwindPlayground.elm
> +        -- div [ class "preview primary-button" ]
sure. It was because of a merge conflict after updating from main. I have to refactor this branch...

2022-02-11 09:37 UTC, kilchenmann commented on src/TailwindPlayground.elm
> +            , CircularButton.view { size = Buttons.Shared.ExtraSmall, icon = "annotation" }
Resolved in 582d82b

2022-02-14 09:24 UTC, merged